create extension if not exists "pgcrypto";
create type user_role as enum ('admin', 'editor', 'analyst');
create type content_status as enum ('draft', 'published', 'archived');
create type partner_status as enum ('active', 'inactive');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null unique, full_name text, role user_role not null default 'analyst', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, display_order int not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.subcategories (id uuid primary key default gen_random_uuid(), category_id uuid references public.categories(id) on delete set null, name text not null, slug text not null unique, description text, display_order int not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.collections (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, hero_image_url text, is_active boolean not null default true, starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.affiliate_partners (id uuid primary key default gen_random_uuid(), name text not null, logo_url text, domain text, affiliate_code text not null, affiliate_param text not null default 'ref', url_template text, commission_rate numeric(8,2) default 0, cookie_duration_days int default 30, status partner_status not null default 'active', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, sku text unique, short_description text, description text, current_price numeric(12,2), old_price numeric(12,2), installments text, discount_percent numeric(5,2), category_id uuid references public.categories(id) on delete set null, subcategory_id uuid references public.subcategories(id) on delete set null, collection_id uuid references public.collections(id) on delete set null, material text, plating text, stone text, color text, sizes text[] default '{}', main_image_url text, badge text, is_featured boolean not null default false, is_new boolean not null default false, is_promo boolean not null default false, display_order int not null default 0, original_url text, affiliate_url text, affiliate_partner_id uuid references public.affiliate_partners(id) on delete set null, estimated_commission numeric(12,2) default 0, seo_title text, seo_description text, status content_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, image_url text not null, alt_text text, display_order int not null default 0, is_main boolean not null default false, created_at timestamptz not null default now());
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, name text not null, sku text, size text, color text, price numeric(12,2), stock_status text default 'available', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.affiliate_clicks (id uuid primary key default gen_random_uuid(), product_id uuid references public.products(id) on delete set null, affiliate_partner_id uuid references public.affiliate_partners(id) on delete set null, clicked_at timestamptz not null default now(), source text, referrer text, utm_source text, utm_medium text, utm_campaign text, utm_content text, utm_term text, user_agent text, ip_hash text, clicked_url text, estimated_commission numeric(12,2) default 0);
create table public.banners (id uuid primary key default gen_random_uuid(), title text not null, subtitle text, image_url text, button_label text, button_url text, placement text not null default 'home', display_order int not null default 0, is_active boolean not null default true, starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.homepage_sections (id uuid primary key default gen_random_uuid(), section_key text not null unique, title text, subtitle text, content jsonb not null default '{}'::jsonb, display_order int not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.leads (id uuid primary key default gen_random_uuid(), email text not null unique, name text, source text, status text not null default 'new', consent_at timestamptz default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.pages (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, body text, seo_title text, seo_description text, status text not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.site_settings (id uuid primary key default gen_random_uuid(), key text not null unique, value jsonb not null default '{}'::jsonb, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id) on delete set null, action text not null, table_name text not null, record_id uuid, changes jsonb, created_at timestamptz not null default now());

create index idx_products_status_order on public.products(status, display_order);
create index idx_products_slug on public.products(slug);
create index idx_products_category on public.products(category_id);
create index idx_clicks_product_date on public.affiliate_clicks(product_id, clicked_at desc);
create index idx_clicks_partner_date on public.affiliate_clicks(affiliate_partner_id, clicked_at desc);
create index idx_clicks_utm on public.affiliate_clicks(utm_source, utm_campaign);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.current_role() returns user_role language sql stable as $$ select role from public.profiles where id = auth.uid() and is_active = true; $$;
create or replace function public.is_admin() returns boolean language sql stable as $$ select coalesce(public.current_role() = 'admin', false); $$;
create or replace function public.can_edit_content() returns boolean language sql stable as $$ select coalesce(public.current_role() in ('admin', 'editor'), false); $$;
create or replace function public.can_view_admin() returns boolean language sql stable as $$ select coalesce(public.current_role() in ('admin', 'editor', 'analyst'), false); $$;

create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger set_products_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger set_categories_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger set_subcategories_updated_at before update on public.subcategories for each row execute function public.set_updated_at();
create trigger set_collections_updated_at before update on public.collections for each row execute function public.set_updated_at();
create trigger set_partners_updated_at before update on public.affiliate_partners for each row execute function public.set_updated_at();
create trigger set_banners_updated_at before update on public.banners for each row execute function public.set_updated_at();
create trigger set_home_updated_at before update on public.homepage_sections for each row execute function public.set_updated_at();
create trigger set_pages_updated_at before update on public.pages for each row execute function public.set_updated_at();
create trigger set_settings_updated_at before update on public.site_settings for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.collections enable row level security;
alter table public.product_variants enable row level security;
alter table public.affiliate_partners enable row level security;
alter table public.affiliate_clicks enable row level security;
alter table public.banners enable row level security;
alter table public.homepage_sections enable row level security;
alter table public.leads enable row level security;
alter table public.pages enable row level security;
alter table public.site_settings enable row level security;
alter table public.audit_logs enable row level security;

create policy "public published products" on public.products for select using (status = 'published' or public.can_view_admin());
create policy "edit products" on public.products for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "public active categories" on public.categories for select using (is_active or public.can_view_admin());
create policy "edit categories" on public.categories for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "public active subcategories" on public.subcategories for select using (is_active or public.can_view_admin());
create policy "edit subcategories" on public.subcategories for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "public active collections" on public.collections for select using (is_active or public.can_view_admin());
create policy "edit collections" on public.collections for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "public product images" on public.product_images for select using (exists (select 1 from public.products p where p.id = product_id and p.status = 'published') or public.can_view_admin());
create policy "edit product images" on public.product_images for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "edit variants" on public.product_variants for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "view partners as admin" on public.affiliate_partners for select using (public.can_view_admin());
create policy "edit partners as admin" on public.affiliate_partners for all using (public.is_admin()) with check (public.is_admin());
create policy "insert clicks publicly" on public.affiliate_clicks for insert with check (true);
create policy "view clicks as analyst" on public.affiliate_clicks for select using (public.can_view_admin());
create policy "public active banners" on public.banners for select using (is_active or public.can_view_admin());
create policy "edit banners" on public.banners for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "public active home sections" on public.homepage_sections for select using (is_active or public.can_view_admin());
create policy "edit home sections" on public.homepage_sections for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "insert leads publicly" on public.leads for insert with check (true);
create policy "manage leads admin" on public.leads for all using (public.is_admin()) with check (public.is_admin());
create policy "public published pages" on public.pages for select using (status = 'published' or public.can_view_admin());
create policy "edit pages" on public.pages for all using (public.can_edit_content()) with check (public.can_edit_content());
create policy "public settings read" on public.site_settings for select using (true);
create policy "edit settings admin" on public.site_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "own profile read" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "admin manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());
create policy "view audit logs" on public.audit_logs for select using (public.is_admin());
create policy "insert audit logs" on public.audit_logs for insert with check (public.can_view_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('product-images', 'product-images', true, 4194304, array['image/jpeg','image/png','image/webp']), ('banners', 'banners', true, 4194304, array['image/jpeg','image/png','image/webp']) on conflict (id) do nothing;
create policy "public read product images" on storage.objects for select using (bucket_id in ('product-images', 'banners'));
create policy "admin upload product images" on storage.objects for insert with check (bucket_id in ('product-images', 'banners') and public.can_edit_content());
create policy "admin update product images" on storage.objects for update using (bucket_id in ('product-images', 'banners') and public.can_edit_content());
create policy "admin delete product images" on storage.objects for delete using (bucket_id in ('product-images', 'banners') and public.can_edit_content());